name: fdupes_gui
description: fdupes front-end
publish_to: 'none'
version: 0.3.1+7

dependency_overrides:
  image:
    git:
      url: https://github.com/mx1up/image.git
      ref: fix_add_frame_on_empty_image

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.13.9"

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^4.2.0
  process_run: ^0.13.2
  file_selector: ^1.0.1
  flutter_bloc: ^8.1.3
  url_launcher: ^6.2.1
  open_file: ^3.3.2
  path: ^1.8.3
  adaptive_theme: ^3.4.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/mx1up/flutter_launcher_icons.git
      ref: multi_res_ico

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon_256.png

flutter_launcher_icons:
  windows:
    image_path: "assets/app_icon_256.png"
    generate: true