name: build

on:
  workflow_call:
    inputs:
      build-windows:
        required: false
        type: boolean
        default: true
      build-linux:
        required: false
        type: boolean
        default: true
      build-macos:
        required: false
        type: boolean
        default: true

env:
  FLUTTER_VERSION: 3.13.9

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux build dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Build Linux app
        run: flutter build linux --verbose

      - name: Archive (preserve permissions)
        run: tar cvfz linux-build.tar.gz -C build/linux/x64/release/bundle .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: linux-build.tar.gz

  build-macos:
    name: Build on macOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: |
          flutter build macos
          mkdir build/macos/Build/Products/Release/artifact
          mv build/macos/Build/Products/Release/fdupes_gui.app build/macos/Build/Products/Release/artifact/

      - name: Archive (preserve permissions)
        run: tar cvfz macos-build.tar.gz -C build/macos/Build/Products/Release/artifact .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: macos-build.tar.gz

