name: release builds

on:
  workflow_dispatch:
  push:
    tags:
      - 'release/*'

permissions:
  contents: write

env:
  FLUTTER_VERSION: 3.13.9

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from tag
        id: release_info
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/release/}
          NOTES=$(awk "/^## $VERSION/ {flag=1; next} /^## / {if (flag) exit} flag" CHANGELOG.md)
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.release_info.outputs.version }}"
          body: ${{ steps.release_info.outputs.notes }}
          files: build/windows/runner/Release/

#      - name: Upload release asset
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows-installer
#          path: build/windows/runner/Release/

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux build dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Build Linux App
        run: flutter build linux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.release_info.outputs.version }}"
          body: ${{ steps.release_info.outputs.notes }}
          files: /build/linux/x64/release/bundle

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: linux-installer
#          path: /build/linux/x64/release/bundle

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.release_info.outputs.version }}"
          body: ${{ steps.release_info.outputs.notes }}
          files: build/macos/Build/Products/Release/fdupes_gui.app

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: macos-installer
#          path: build/macos/Build/Products/Release/fdupes_gui.app

